### PR TITLE
fix: enforce eslint configuration

### LINKED ISSUE #116: Multi-word component name
authenticate.component.vue -> AuthenticateComponent.vue

### PR DESCRIPTION
**Pull request by kuamanet**
Fix #116

### CODE REVIEW

File: web-app/src/auth/pages/authenticate-page.component.vue [hunk 1]
```diff
@@ -0,0 +1,5 @@
+<template>
+  <p>TODO we plan on showing sign up & sign in the same page</p>
```
Comment (salvanicola) [inline web-app/src/auth/pages/authenticate-page.component.vue]: Why always appears as a diff?

**Review by salvanicola — APPROVED** [review]
